# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  # - id: check-docstring-first
  - id: check-json
  - id: check-merge-conflict
  - id: check-shebang-scripts-are-executable
  - id: check-symlinks
  - id: check-toml
  - id: check-yaml
    args: ['--allow-multiple-documents', '--unsafe']
    exclude: template.ya?ml$
  - id: debug-statements
  - id: detect-aws-credentials
    args: ['--allow-missing-credentials']
  # - id: detect-private-key # kubernetes/argocd/cluster-management/helm-values/argocd.yml
  - id: end-of-file-fixer
  - id: mixed-line-ending
    args: [ --fix=lf ]
  - id: name-tests-test
    args: ['--pytest-test-first']
  - id: requirements-txt-fixer
  - id: trailing-whitespace

- repo: https://github.com/psf/black
  rev: 25.1.0
  hooks:
  - id: black
    language: python
    args: [".", "-l", "120"]  # Set line length to 120

- repo: https://github.com/PyCQA/isort
  rev: 6.0.1
  hooks:
  - id: isort
    args: ["--profile", "black"]  # Use black profile

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.15.0'
  hooks:
  - id: mypy
    language: system
    args: ["--follow-imports=silent", "--strict", "--ignore-missing-imports"]
    exclude: "tests|dist|experiments"

- repo: https://github.com/PyCQA/bandit
  rev: 1.8.3
  hooks:
  - id: bandit
    stages: [manual]
    name: Bandit vulnerability check
    args:
    - -c=bandit.yml
    - --recursive
    - -lll
    - .
    always_run: True
    pass_filenames: False

- repo: https://github.com/jorisroovers/gitlint
  rev: v0.19.1
  hooks:
  - id: gitlint
    stages: [commit-msg]

- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.98.1
  hooks:
    - id: terraform_fmt # Not working recursively...
    # - id: terraform_checkov
    #   args:
    #     - --args=--quiet
    #     - --args=--skip-path=terraform/modules

- repo: local
  hooks:
    - id: pytest-check
      name: pytest-check
      entry: pytest
      language: system
      pass_filenames: false
      always_run: true
